# Generated by Django 4.2.3 on 2023-09-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_additionalpricepayment_orderpayment_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpayment',
            old_name='order_id',
            new_name='order_number',
        ),
    ]
