# Generated by Django 4.2.3 on 2023-08-04 21:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Pakistan', 'Pakistan'), ('Bangladesh', 'Bangladesh'), ('Russia', 'Russia'), ('China', 'China')], default='India', max_length=20)),
                ('user_address', models.TextField(default='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type', models.CharField(choices=[('Regular', 'Regular Order'), ('Simple', 'Sample Order'), ('Urgent', 'Urgent order')], default='Regular', max_length=10)),
                ('purchaser', models.CharField(blank=True, max_length=100, null=True)),
                ('salesman', models.CharField(blank=True, max_length=100, null=True)),
                ('requirements_remarks', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('active', 'Active'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('modification', 'Modification')], default='active', max_length=12, null=True)),
                ('original_data', models.CharField(choices=[('Raw Scanned Data', 'Raw Scanned Data')], default='Raw Scanned Data', max_length=20)),
                ('design_printing', models.CharField(choices=[('Design', 'Design')], default='Design', max_length=50)),
                ('product_type', models.CharField(choices=[('Cobalt-chrome framework - Design Fee', 'Cobalt-chrome framework - Design Fee')], default='Cobalt-chrome framework - Design Fee', max_length=100)),
                ('product_sub_type', models.CharField(choices=[('Anatomic Full Crown', 'Anatomic Full Crown '), ('Veneer ( Emax, Ivoclar)', 'Veneer ( Emax, Ivoclar)'), ('Inlay/Onlay', 'Inlay/Onlay'), ('Smile Creator', 'Smile Creator'), ('Acrylic Temporary Crowns', 'Acrylic Temporary Crowns'), ('Custom Implant Abutment', 'Custom Implant Abutment'), ('Cast Partial Denture Framework (upto 3 unit single arch)', 'Cast Partial Denture Framework (upto 3 unit single arch)'), ('Cast Partial Denture Framework (upto 6 unit single arch)', 'Cast Partial Denture Framework (upto 6 unit single arch)'), ('Cast Partial Denture Framework (upto 13 unit single arch)', 'Cast Partial Denture Framework (upto 13 unit single arch)'), ('Screw retained crown', 'Screw Retained Crown'), ('CO-CR framework', 'CO-CR framework'), ('Zirconia\xa0Framework', 'Zirconia\xa0Framework'), ('All on 4/6 implants', 'All on 4/6 implants'), ('Implant SLM malo bridge', 'Implant SLM Malo Bridge '), ('Implant Hybrid Denture', 'Implant Hybrid Denture'), ('Cast Partial Obturator', 'Cast Partial Obturator'), ('Bridge Framework', 'Bridge Framework'), ('Bite Splint', 'Bite Splint'), ('Full Mouth Rehabilitation', 'Full Mouth Rehabilitation'), ('Wax-up for smile correction', 'Wax-up for smile correction '), ('Contact Model ( each quadrant )', 'Contact Model ( each quadrant )'), ('Contact Model with extra die  ( each quadrant )', 'Contact Model with extra die  ( each quadrant )'), ('Models with articulation (uppr/lower)', 'Models with articulation (uppr/lower)'), ('Study Model (Full Mouth)', 'Study Model (Full Mouth)'), ('Surgical guide', 'Surgical Guide')], default='Anatomic Full Crown', max_length=100)),
                ('product_material', models.CharField(choices=[('OCOR', 'OCOR'), ('Metal ', 'Metal'), ('Resin', 'Resin'), ('Zirconia / Metal / PMMA ', 'Zirconia / Metal / PMMA '), ('Zirconia / Emax', 'Zirconia / Emax'), ('Wax', 'Wax'), ('PMMA', 'PMMA'), ('Zirconia / Metal', 'Zirconia / Metal ')], default='OCOR', max_length=50)),
                ('unit_of_measurement', models.CharField(choices=[('PCS', 'PCS')], default='PCS', max_length=10)),
                ('currency', models.CharField(choices=[('USA', 'USD (Dollar)'), ('INR', 'INR (Indian Rupees)')], default='USA', max_length=10)),
                ('quantity', models.IntegerField()),
                ('delivery_timing', models.CharField(choices=[('12HRS', '12 HRS'), ('6HRS', '6 HRS'), ('2HRS', '2 HRS')], default='12HRS', max_length=10)),
                ('file_upload_required', models.FileField(upload_to='uploads/files/stl-dcm-html')),
                ('design_requirement', models.FileField(default='', upload_to='uploads/files/otherfiles')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
