# Generated by Django 4.2.3 on 2023-09-20 16:51

import amruloapp.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, storage=amruloapp.storage.OverwriteStorage(), upload_to='')),
                ('phone', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('approval_status', models.BooleanField(default=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('user_address', models.TextField(default='')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_phone', models.CharField(max_length=15)),
                ('company_address', models.TextField()),
                ('company_bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(editable=False, max_length=3, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Framework Agreements',
            },
        ),
        migrations.CreateModel(
            name='FrameworkInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperation_mode_content', models.TextField(blank=True, null=True)),
                ('payment_method_content', models.TextField(blank=True, null=True)),
                ('processing_quantity_content', models.TextField(blank=True, null=True)),
                ('price_adjustment_content', models.TextField(blank=True, null=True)),
                ('shipping_method_content', models.TextField(blank=True, null=True)),
                ('product_acceptance_content', models.TextField(blank=True, null=True)),
                ('number_management_content', models.TextField(blank=True, null=True)),
                ('breach_contract_content', models.TextField(blank=True, null=True)),
                ('force_majeure_content', models.TextField(blank=True, null=True)),
                ('order_effect_content', models.TextField(blank=True, null=True)),
                ('sign_confirmation_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_status', models.CharField(blank=True, choices=[('review', 'Review'), ('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='review', max_length=12, null=True)),
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type', models.CharField(choices=[('Regular', 'Regular Order'), ('Simple', 'Sample Order'), ('Urgent', 'Urgent order')], default='Regular', max_length=10)),
                ('purchaser', models.CharField(blank=True, max_length=100, null=True)),
                ('salesman', models.CharField(blank=True, max_length=100, null=True)),
                ('requirements_remarks', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USA', 'USD (Dollar)'), ('INR', 'INR (Indian Rupees)')], default='USA', max_length=10)),
                ('design_requirement', models.FileField(default='', upload_to='uploads/files/otherfiles')),
                ('file_upload_required', models.FileField(upload_to='uploads/files/stl-dcm-html')),
                ('remake_notes', models.TextField(blank=True)),
                ('num_crowns', models.PositiveIntegerField(default=0)),
                ('num_brackets', models.PositiveIntegerField(default=0)),
                ('remake_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('attachment_zip_rar', models.FileField(blank=True, null=True, upload_to='uploads/files/zip-rar-attch/')),
                ('att_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amruloapp.companyinformation')),
                ('delivery_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.deliverytiming')),
                ('design_printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.designprinting')),
                ('framework_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amruloapp.frameworkagreement')),
                ('original_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.originaldata')),
                ('product_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmaterial')),
                ('product_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubtype')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unitofmeasurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amruloapp.companyinformation'),
        ),
    ]
