# Generated by Django 4.2.3 on 2023-07-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0002_order_delivery_timing_prices_alter_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_timing_prices',
        ),
    ]
