# Generated by Django 4.2.3 on 2023-12-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0002_remove_order_unit_of_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_password',
        ),
    ]
