# Generated by Django 4.2.3 on 2023-07-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0003_remove_order_delivery_timing_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='model_design',
        ),
        migrations.RemoveField(
            model_name='order',
            name='typesetting_printing',
        ),
        migrations.AddField(
            model_name='order',
            name='design_printing',
            field=models.CharField(choices=[('Design', 'Design')], default='Design', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USA', 'USD (Dollar)'), ('INR', 'INR (Indian Rupees)')], default='USA', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='original_data',
            field=models.CharField(choices=[('Raw Scanned Data', 'Raw Scanned Data')], default='Raw Scanned Data', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_sub_type',
            field=models.CharField(choices=[('Anatomic Full Crown', 'Anatomic Full Crown '), ('Veneer ( Emax, Ivoclar)', 'Veneer ( Emax, Ivoclar)'), ('Inlay/Onlay', 'Inlay/Onlay'), ('Smile Creator', 'Smile Creator'), ('Acrylic Temporary Crowns', 'Acrylic Temporary Crowns'), ('Custom Implant Abutment', 'Custom Implant Abutment'), ('Cast Partial Denture Framework (upto 3 unit single arch)', 'Cast Partial Denture Framework (upto 3 unit single arch)'), ('Cast Partial Denture Framework (upto 6 unit single arch)', 'Cast Partial Denture Framework (upto 6 unit single arch)'), ('Cast Partial Denture Framework (upto 13 unit single arch)', 'Cast Partial Denture Framework (upto 13 unit single arch)'), ('Screw retained crown', 'Screw Retained Crown'), ('All on 4/6 implants', 'All on 4/6 implants'), ('Implant SLM malo bridge', 'Implant SLM Malo Bridge '), ('Implant Hybrid Denture', 'Implant Hybrid Denture'), ('Cast Partial Obturator', 'Cast Partial Obturator'), ('Bridge Framework', 'Bridge Framework'), ('Bite Splint', 'Bite Splint'), ('Full Mouth Rehabilitation', 'Full Mouth Rehabilitation'), ('Wax-up for smile correction', 'Wax-up for smile correction '), ('Contact Model ( each quadrant )', 'Contact Model ( each quadrant )'), ('Contact Model with extra die  ( each quadrant )', 'Contact Model with extra die  ( each quadrant )'), ('Models with articulation (uppr/lower)', 'Models with articulation (uppr/lower)'), ('Study Model (Full Mouth)', 'Study Model (Full Mouth)'), ('Surgical guide', 'Surgical Guide')], default='Anatomic Full Crown', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_type',
            field=models.CharField(choices=[('Cobalt-chrome framework - Design Fee', 'Cobalt-chrome framework - Design Fee')], default='Cobalt-chrome framework - Design Fee', max_length=100),
        ),
    ]
