# Generated by Django 4.2.3 on 2023-08-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0004_remove_order_model_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_requirement',
            field=models.FileField(default='', upload_to='uploads/files/otherfiles'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file_upload_required',
            field=models.FileField(upload_to='uploads/files/stl-dcm'),
        ),
    ]
