# Generated by Django 4.2.3 on 2023-09-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
