# Generated by Django 4.2.3 on 2023-09-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0005_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
