# Generated by Django 4.2.3 on 2023-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0005_order_design_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchaser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='requirements_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='salesman',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
