# Generated by Django 4.2.3 on 2023-07-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0005_remove_order_production_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='num_of_files',
        ),
        migrations.AddField(
            model_name='order',
            name='model_design',
            field=models.CharField(choices=[('Contact Model ( each quadrant )', 'Contact Model ( each quadrant )'), ('Contact Model with extra die  ( each quadrant )', 'Contact Model with extra die  ( each quadrant )'), ('Models with articulation (uppr/lower)', 'Models with articulation (uppr/lower)'), ('Study Model (Full Mouth)', 'Study Model (Full Mouth)'), ('Surgical guide ', 'Surgical Guide')], default='Contact Model ( each quadrant )', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Pakistan', 'Pakistan'), ('Bangladesh', 'Bangladesh'), ('Russia', 'Russia'), ('China', 'China')], default='India', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USA', 'USA ($)'), ('INR', 'INR (Indian Rupees)')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_timing',
            field=models.CharField(choices=[('12HRS', '12 HRS'), ('6HRS', '6 HRS'), ('2HRS', '2 HRS')], default='12HRS', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Regular', 'Regular Order'), ('Simple', 'Sample Order'), ('Urgent', 'Urgent order')], default='Regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='original_data',
            field=models.CharField(choices=[('Completed Design', 'Completed Design Data'), ('Physical Impression', 'Physical Impression'), ('Raw Scanned Data', 'Raw Scanned Data')], default='Completed Design', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_material',
            field=models.CharField(choices=[('OCOR', 'OCOR'), ('Metal ', 'Metal'), ('Resin', 'Resin'), ('Zirconia / Metal / PMMA ', 'Zirconia / Metal / PMMA '), ('Zirconia / Emax', 'Zirconia / Emax'), ('Wax', 'Wax'), ('PMMA', 'PMMA'), ('Zirconia / Metal', 'Zirconia / Metal ')], default='OCOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_sub_type',
            field=models.CharField(choices=[('Cast Partial Denture Framework (upto 3 unit single arch)', 'Cast Partial Denture Framework (upto 3 unit single arch)'), ('Cast Partial Denture Framework (upto 6 unit single arch)', 'Cast Partial Denture Framework (upto 6 unit single arch)'), ('Cast Partial Denture Framework (upto 13 unit single arch)', 'Cast Partial Denture Framework (upto 13 unit single arch)'), ('Screw retained crown', 'Screw Retained Crown'), ('All on 4/6 implants', 'All on 4/6 implants'), ('Implant SLM malo bridge', 'Implant SLM Malo Bridge '), ('Implant Hybrid Denture', 'Implant Hybrid Denture'), ('Cast Partial Obturator', 'Cast Partial Obturator'), ('Bridge Framework', 'Bridge Framework'), ('Bite Splint', 'Bite Splint'), ('Full Mouth Rehabilitation', 'Full Mouth Rehabilitation'), ('Wax-up for smile correction', 'Wax-up for smile correction ')], default='Cast Partial Denture Framework (upto 3 unit single arch)', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_type',
            field=models.CharField(choices=[('Anatomic Full Crown', 'Anatomic Full Crown '), ('Veneer ( Emax, Ivoclar)', 'Veneer ( Emax, Ivoclar)'), ('Inlay/Onlay', 'Inlay/Onlay'), ('Smile Creator', 'Smile Creator'), ('Acrylic Temporary Crowns', 'Acrylic Temporary Crowns'), ('Inlay/Onlay', 'Inlay/Onlay'), ('Custom Implant Abutment', 'Custom Implant Abutment'), ('Cobalt-chrome framework', 'Cobalt-chrome framework'), ('Titanium Full Contour Crown (TC4)', 'Titanium Full Contour Crown (TC4)'), ('Titanium Framework (TC4)', 'Titanium Framework (TC4)')], default='Anatomic Full Crown', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='typesetting_printing',
            field=models.CharField(choices=[('Nesting & Slicing & Printing', 'Nesting & Slicing & Printing'), ('Nesting & Slicing', 'Nesting & Slicing')], default='Nesting & Slicing & Printing', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_of_measurement',
            field=models.CharField(choices=[('PCS', 'PCS')], default='PCS', max_length=10),
        ),
    ]
