# Generated by Django 4.2.3 on 2023-09-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0006_user_user_password_alter_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
