# Generated by Django 4.2.3 on 2023-09-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0007_order_is_ordered_alter_user_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_ordered',
            new_name='is_paid',
        ),
    ]
