# Generated by Django 4.2.3 on 2023-08-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0008_order_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkagreement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amruloapp.companyinformation'),
        ),
    ]
