# Generated by Django 4.2.3 on 2023-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0008_rename_is_ordered_order_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='add_price_is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='order_is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
