# Generated by Django 4.2.3 on 2023-09-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0009_rename_is_paid_order_add_price_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='add_price_is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_is_paid',
        ),
    ]
