# Generated by Django 4.2.3 on 2023-08-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0009_frameworkagreement_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amruloapp.frameworkagreement'),
        ),
    ]
