# Generated by Django 4.2.3 on 2023-08-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0010_alter_order_agreement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='agreement',
            new_name='framework_agreement',
        ),
    ]
