# Generated by Django 4.2.3 on 2023-09-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0010_remove_order_add_price_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.CreateModel(
            name='OrderGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='uploads/files/gallery')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amruloapp.order')),
            ],
            options={
                'verbose_name': 'Order Gallery',
                'verbose_name_plural': 'Orders Gallery',
            },
        ),
    ]
