# Generated by Django 4.2.3 on 2023-09-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0010_remove_order_add_price_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='attachment_zip_rar',
            field=models.FileField(blank=True, null=True, upload_to='uploads/zip-rar-attch/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='design_requirement',
            field=models.FileField(default='', upload_to='uploads/jpeg-png-files/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file_upload_required',
            field=models.FileField(upload_to='uploads/stl-dcm-html/'),
        ),
    ]
