# Generated by Django 4.2.3 on 2023-09-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0011_alter_order_attachment_zip_rar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='design_requirement',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file_upload_required',
        ),
    ]
