# Generated by Django 4.2.3 on 2023-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0011_alter_order_options_ordergallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design_requirement',
            field=models.FileField(blank=True, upload_to='uploads/files/otherfiles'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file_upload_required',
            field=models.FileField(blank=True, upload_to='uploads/files/stl-dcm-html'),
        ),
    ]
