# Generated by Django 4.2.3 on 2023-08-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0011_rename_agreement_order_framework_agreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frameworkagreement',
            options={'verbose_name_plural': 'Framework Agreements'},
        ),
    ]
