# Generated by Django 4.2.3 on 2023-08-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0012_alter_frameworkagreement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkagreement',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amruloapp.companyinformation'),
        ),
    ]
