# Generated by Django 4.2.3 on 2023-09-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0012_alter_order_design_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergallery',
            name='extension',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
