# Generated by Django 4.2.3 on 2023-09-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0012_remove_order_design_requirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='attachment_zip_rar',
        ),
    ]
