# Generated by Django 4.2.3 on 2023-08-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0013_alter_frameworkagreement_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameworkagreement',
            name='company',
        ),
    ]
