# Generated by Django 4.2.3 on 2023-09-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0013_remove_order_attachment_zip_rar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachment_zip_rar',
            field=models.FileField(blank=True, null=True, upload_to='uploads/zip-rar-attch/'),
        ),
        migrations.AddField(
            model_name='order',
            name='design_requirement',
            field=models.FileField(default='', upload_to='uploads/jpeg-png-files/'),
        ),
        migrations.AddField(
            model_name='order',
            name='file_upload_required',
            field=models.FileField(default=1, upload_to='uploads/stl-dcm-html/'),
            preserve_default=False,
        ),
    ]
