# Generated by Django 4.2.3 on 2023-08-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0014_remove_frameworkagreement_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amruloapp.companyinformation'),
        ),
    ]
