# Generated by Django 4.2.3 on 2023-08-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0016_user_user_status_alter_user_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_status',
        ),
    ]
