# Generated by Django 4.2.3 on 2023-08-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0020_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='affiliated_with',
        ),
        migrations.AddField(
            model_name='order',
            name='att_file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='attachment_zip_rar',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files/zip-rar-attch/'),
        ),
    ]
