# Generated by Django 4.2.3 on 2023-09-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0021_remove_user_affiliated_with_order_att_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperation_mode_content', models.TextField(blank=True, null=True)),
                ('payment_method_content', models.TextField(blank=True, null=True)),
                ('processing_quantity_content', models.TextField(blank=True, null=True)),
                ('price_adjustment_content', models.TextField(blank=True, null=True)),
                ('shipping_method_content', models.TextField(blank=True, null=True)),
                ('product_acceptance_content', models.TextField(blank=True, null=True)),
                ('number_management_content', models.TextField(blank=True, null=True)),
                ('breach_contract_content', models.TextField(blank=True, null=True)),
                ('force_majeure_content', models.TextField(blank=True, null=True)),
                ('order_effect_content', models.TextField(blank=True, null=True)),
                ('sign_confirmation_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
