# Generated by Django 4.2.3 on 2023-12-24 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdlapp', '0002_user_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_password',
        ),
    ]
