# Generated by Django 4.2.3 on 2023-12-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cdlapp', '0004_user_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubtype', verbose_name='products'),
        ),
    ]
