# Generated by Django 4.2.3 on 2024-01-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cdlapp", "0006_order_commentorremarks_alter_order_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="lower_arch",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="upper_arch",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
