# Generated by Django 4.2.3 on 2024-01-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdlapp', '0007_order_lower_arch_order_upper_arch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lower_arch',
            field=models.PositiveIntegerField(default=0, verbose_name='lower alligner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='upper_arch',
            field=models.PositiveIntegerField(default=0, verbose_name='upper alligner'),
        ),
    ]
