# Generated by Django 4.2.3 on 2023-11-05 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DesignPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product6HrsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.deliverytiming')),
                ('product_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubtype')),
            ],
        ),
        migrations.CreateModel(
            name='Product2HrsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.deliverytiming')),
                ('product_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubtype')),
            ],
        ),
        migrations.CreateModel(
            name='Product12HrsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.deliverytiming')),
                ('product_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubtype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group1', models.BooleanField(default=False)),
                ('group2', models.BooleanField(default=False)),
                ('group3', models.BooleanField(default=False)),
                ('design_printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.designprinting')),
                ('original_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.originaldata')),
                ('product_12hrs_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product12hrsprice')),
                ('product_2hrs_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product2hrsprice')),
                ('product_6hrs_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product6hrsprice')),
                ('product_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmaterial')),
                ('product_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubtype')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unitofmeasurement')),
            ],
        ),
    ]
