# Generated by Django 4.2.3 on 2023-11-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amruloapp', '0002_remove_order_unit_of_measurement'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measurement',
        ),
        migrations.DeleteModel(
            name='UnitOfMeasurement',
        ),
    ]
